
name: "Deploy Terraform Configuration"

on:
  push:
    branches:
    - develop
    paths:
    - '**.tf'
    - '.github/workflows/terraform.yml'  # Adjust the path/name as necessary

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: "1.0.0"
  
    - name: Terraform Init
      run: terraform init

     # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_REGION: 'us-east-2'
