name: "Deploy Terraform Configuration"

on:
  push:
    branches:
      - develop
    paths:
      - '**.tf'
      - '.github/workflows/terraform.yml'  # Ensure this path is correct

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3  # Assuming v2 is the latest stable release
      with:
        terraform_version: "1.0.0"
  
    - name: Initialize Terraform
      run: terraform init

    - name: Check Terraform Format
      run: |
        if ! terraform fmt -check; then
          echo "Terraform files need to be formatted. Please run 'terraform fmt' locally and push the formatted changes."
          exit 1
        fi

    - name: Plan Terraform Changes
      run: terraform plan 

    - name: Apply Terraform Changes
      run: |
        export TF_LOG=DEBUG
        terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'
